### ISSUE TITLE
I want to know if no replication between two pgbench_history tables, i got COUNT=0 for target

### ISSUE THREAD

**Issue by Xuquansheng** [m99coder/pg15-logical-replication-row-filter#1]
When I ran "make validate",comparing two sides, last pair is not same, others are same.

**Comment by Xuquansheng** [comment]
bbalance
----------
     6548
(1 row)

  sum
--------
 -40823
(1 row)

  sum
--------
 -21571
(1 row)

 count
-------
   993
(1 row)

 bbalance
----------
     6548
(1 row)

  sum
--------
 -40823
(1 row)

  sum
--------
 -21571
(1 row)

 count
-------
     0
(1 row)

**Comment by m99coder** [comment]
Hallo Xuquan Sheng (I hope that’s correct),

Thanks for reaching out. I just re-run the flow to make sure it works as expected like that:

```shell
# start both database instances
make start

# create schema in both instances
# create publication
# create subscription
make prepare -j 2

# populate data in both instances
make run -j 2

# validate replication
make validate

# reset data in both instances
make reset -j 3

# stop both database instances
make stop
```

For me the numbers are consistent.

Would you mind sharing the sequence of `make` commands you were running? Also make sure to reset the database instances (use `make reset -j 3`) if you are not starting from scratch (after `make stop`).

All the best,
Marco

**Comment by Xuquansheng** [comment]
Hello, Marco
Thanks for your quick response.
At first, I tried to follow your steps, but failed on step two "make prepare -j 2", i got message below:

[root@superset pg15-logical-replication-row-filter]# make prepare -j 2
```
docker exec -it ${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) pgbench -i -I dtvp -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB}"
docker exec -it ${CONTAINER_NAME_PREFIX}-target /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) pgbench -i -I dtvp -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB}"
```


unknown shorthand flag: 's' in -source
See 'docker exec --help'.
make: *** [Makefile:44: pginitpub] Error 125
make: *** Waiting for unfinished jobs....
unknown shorthand flag: 'a' in -arget
See 'docker exec --help'.

so, i had to go through Makefile and created a script file as below:
[root@superset pg15-logical-replication-row-filter]# more s
#git clone https://github.com/m99coder/pg15-logical-replication-row-filter

cp .envrc .env
docker compose up -d
sleep 15

S="docker exec -it pg15-repl-source /bin/bash -c"
T="docker exec -it pg15-repl-target /bin/bash -c"
H="-h localhost -p 5432 -U demo demo"

$S "PGPASSWORD=demo pgbench -i -I dtvp $H"
$S "PGPASSWORD=demo psql $H < /opt/sql/pgbench_alter.sql"
$S "PGPASSWORD=demo psql $H < /opt/sql/pgbench_init_pub.sql"
$S "PGPASSWORD=demo psql $H < /opt/sql/repl_pub.sql"

$T "PGPASSWORD=demo pgbench -i -I dtvp $H"
$T "PGPASSWORD=demo psql $H < /opt/sql/pgbench_alter.sql"
$T "PGPASSWORD=demo psql $H < /opt/sql/pgbench_init_sub.sql"
$T "PGPASSWORD=demo psql $H < /opt/sql/repl_sub.sql"


$S "PGPASSWORD=demo pgbench -c 10 -j 2 -t 10000 -s 100 -f /opt/bench/pub.bench --verbose-errors $H"
$T "PGPASSWORD=demo pgbench -c 10 -j 2 -t 10000 -s 100 -f /opt/bench/sub.bench --verbose-errors $H"

$S "PGPASSWORD=demo psql $H < /opt/sql/validate.sql"
$T "PGPASSWORD=demo psql $H < /opt/sql/validate.sql"

for me, the number for pgbench_history on target is always 0 , i don't know where is wrong.

**Comment by m99coder** [comment]
Hallo Xuquan,

Please check that the environment variables are set in your shell. I’m using `direnv` which automatically sources the `.envrc` and exports the required environment variables. I assume that line 44 of the Makefile (where the error in your case occurs), is not providing a valid container name:

```shell
docker exec -it $${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$$(echo $$POSTGRES_PASSWORD) pgbench -i -I dtvp -h localhost -p 5432 -U $${POSTGRES_USER} $${POSTGRES_DB}"
```

The expression `$${CONTAINER_NAME_PREFIX}-source` in the Makefile should be resolved to `pg15-repl-source` if you use the default values for the environment variables from `.envrc`.

You can also check the container names used by looking at the `NAMES` column of the running containers like this:

```shell
→ make start
…

→ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED        STATUS                           PORTS      NAMES
cdc5ec03e5b4   postgres:15.4-alpine   "docker-entrypoint.s…"   1 second ago   Up 1 second (health: starting)   5432/tcp   pg15-repl-target
b19fd36769ee   postgres:15.4-alpine   "docker-entrypoint.s…"   1 second ago   Up 1 second (health: starting)   5432/tcp   pg15-repl-source
```

All the best,
Marco

**Comment by Xuquansheng** [comment]
i just installed direnv,still have a problem with "make prepare -j 2",  pginitsub didn't run. below is message:

[root@superset pg15-logical-replication-row-filter]# make prepare -j 2
docker exec -it ${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) pgbench -i -I dtvp -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB}"
docker exec -it ${CONTAINER_NAME_PREFIX}-target /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) pgbench -i -I dtvp -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB}"
the input device is not a TTY
make: *** [Makefile:51: pginitsub] Error 1
                                          make: *** Waiting for unfinished jobs....
                                                                                   dropping old tables...
NOTICE:  table "pgbench_accounts" does not exist, skipping
NOTICE:  table "pgbench_branches" does not exist, skipping
NOTICE:  table "pgbench_history" does not exist, skipping
NOTICE:  table "pgbench_tellers" does not exist, skipping
creating tables...
vacuuming...
creating primary keys...
done in 0.02 s (drop tables 0.00 s, create tables 0.01 s, vacuum 0.00 s, primary keys 0.01 s).
docker exec -it ${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) psql -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB} < /opt/sql/pgbench_alter.sql"
BEGIN
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
COMMIT
docker exec -it ${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) psql -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB} < /opt/sql/pgbench_init_pub.sql"
BEGIN
INSERT 0 50
INSERT 0 500
INSERT 0 5000000
COMMIT
docker exec -it ${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) psql -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB} < /opt/sql/repl_pub.sql"
CREATE PUBLICATION

**Comment by m99coder** [comment]
Which shell (Bash, zsh, fish, …) are you using and on which system are you (macOS, Linux, Windows, …)?

**Comment by Xuquansheng** [comment]
Bash on Rocky Linux.

**Comment by Xuquansheng** [comment]
bash on Rocky Linux

**Comment by m99coder** [comment]
Hi Xuquan,

you can try to modify the `Makefile` in a way that the `docker exec` commands don’t use `-it` anymore, but just `-i` (as described [here](https://stackoverflow.com/a/43099210)). The error `the input device is not a TTY` might be the real reason why the setup doesn’t work on your machine.

All the best,
Marco

**Comment by Xuquansheng** [comment]
Yes, it works now, thank you very much, Marco. below is correct message:

[root@superset pg15-logical-replication-row-filter]# make validate
docker exec -i ${CONTAINER_NAME_PREFIX}-source /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) psql -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB} < /opt/sql/validate.sql"
 bbalance
----------
   -73818
(1 row)

  sum
--------
 -66759
(1 row)

  sum
-------
 22662
(1 row)

 count
-------
   958
(1 row)

docker exec -i ${CONTAINER_NAME_PREFIX}-target /bin/bash -c "PGPASSWORD=$(echo $POSTGRES_PASSWORD) psql -h localhost -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB} < /opt/sql/validate.sql"
 bbalance
----------
   -73818
(1 row)

  sum
--------
 -66759
(1 row)

  sum
-------
 22662
(1 row)

 count
-------
   958
(1 row)

**Comment by Xuquansheng** [comment]
I  tested this wonderful project against latest postgres 16, it works also, thanks again.

**Comment by m99coder** [comment]
Glad the project provides value to you as well 👍
